name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          ls
          docker pull aergus/latex
          docker run --rm -v $(pwd):/docs aergus/latex /bin/bash -c "ls; cd docs; pdflatex Untitled.tex"
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: doc.pdf
          path: .
