name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          docker pull aergus/latex
          docker run --rm -v $(pwd):/docs aergus/latex /bin/bash -c "cd docs; pdflatex Untitled.tex"
